import * as React from "react"
import {Box, Button, FormControl, InputLabel, MenuItem, Select, Typography} from "@mui/material";
import {getAllToolTypes, getOrderedToolUsage, ToolType, ToolUsage} from "../../utils/DataManager";
import Skill from "../../components/Text/Skill";
import {Section, SectionElement} from "../../components/Section/Section";
import Lang from "../../components/Lang/Lang";
import Link from 'next/link'
import {useEffect, useState} from "react";

interface Props {
  expanded: boolean;
}

const styles = {
  pageContainer: {
    backgroundColor: 'black',
    color: 'white',
  },
  titleContainer: {
    paddingTop: "40px",
    paddingBottom: "80px",
  },
  title: {
    fontSize: 25,
    fontWeight: 'bold',
  },
  subsubTitle: {
    fontSize: 13,
  },
  subTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    paddingBottom: '20px',
  },
  divider: {
    height: '20px',
  },
};

function HardSkills({expanded} : Props) {

  const usages = getOrderedToolUsage();
  const maxFeatured = 3;

  const types = getAllToolTypes();
  const [selectedType, setSelectedType] = useState<ToolType | "all">("all");
  const [splitted, setSplitted] = useState<ToolUsage[][]>([[], [], []])

  useEffect(() => {
    const temp = [[], [], []];
    const filteredTools = usages.filter(tu => selectedType === "all" || selectedType === tu.data.type);
    for (let i = 0; i < filteredTools.length; i++) {
      if(!expanded && i >= maxFeatured)
        break;

      temp[i%3].push(filteredTools[i]);
    }

    setSplitted(temp);
  }, [selectedType]);


  return (
    <div style={styles.pageContainer}>
      <Box sx={styles.titleContainer}>
        <Typography sx={styles.title}><Lang identifier="tools.title"/></Typography>
        <Typography sx={styles.subsubTitle}><Lang identifier="common.autogenerated"/></Typography>
      </Box>

      {!expanded && <Typography sx={styles.subTitle}><Lang identifier="tools.most_used"/></Typography>}

      <FormControl>
        <InputLabel id="select-label"><Lang identifier="tools.type.name"/></InputLabel>
        <Select
            labelId="select-label"
            value={selectedType}
            label="Age"
            variant='outlined'
            onChange={v => setSelectedType(v.target.value as ToolType)}
        >
          <MenuItem value={"all"}><Lang identifier={"tools.type.all"}/></MenuItem>
          {types.map(type => (
              <MenuItem key={type} value={type}><Lang identifier={"tools.type." + type}/></MenuItem>
          ))}
        </Select>
      </FormControl>

      <Section color='black'>
        <SectionElement>
          {splitted[0].map((tu, i) => {
            return ([
              <Skill key='skill' usage={tu}/>,
              <div key='div' style={styles.divider}></div>,
            ])
          })
          }
        </SectionElement>
        <SectionElement>
          {splitted[1].map((tu, i) => {
            return ([
              <Skill key='skill' usage={tu}/>,
              <div key='div' style={styles.divider}></div>,
            ])
          })
          }
        </SectionElement>
        <SectionElement>
          {splitted[2].map((tu, i) => {
            return ([
              <Skill key='skill' usage={tu}/>,
              <div key='div' style={styles.divider}></div>,
            ])
          })
          }
        </SectionElement>
      </Section>

      { !expanded &&
          <Button variant='outlined' component={Link} href="/tools">
              <Lang identifier="common.view_all"/>
          </Button>
      }

    </div>
  )
}

interface ExpandedProps {
  skills: ToolUsage[];
}
function ExpandedSkills({skills} : ExpandedProps) {
  return (
    <div>
      <Typography sx={styles.subTitle}>Other Projects:</Typography>
      {skills.map(tu => {
        return (
          [
            <Skill key='skill' usage={tu}/>,
            <div key='div' style={styles.divider}></div>,
          ]
        )
      })}
    </div>
  )
}

export default HardSkills;